apiVersion: apps/v1
kind: Deployment
metadata:
  name: weblogic-deployment
  labels:
    app: weblogic-deployment # this label servies will use to monitor deplyment pod 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weblogic # this label will let deployment mange pods 
  template:
    metadata:
      labels:
        app: weblogic # pod label
    spec: 
      topologySpreadConstraints: # this will make pods on all nodes 
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app: weblogic ######### end 
      containers:
      - name: weblogic # container name
        image: docker-registry.aot.sa/aot-domian-volume:latest # IMAGE
        imagePullPolicy: Always
        readinessProbe:
            httpGet:
              path: /weblogic/ready
              port: 7001
            initialDelaySeconds: 15
            timeoutSeconds: 5
        env:
          #- name: JAVA_OPTS
          #  value: "-Djava.net.preferIPv4Stack=true -Djava.net.preferIPv4Addressess=true -Dfile.encoding=UTF-8 -Djava.awt.headless=true -XX:+UseG1GC -XX:MinRAMPercentage=50.0 -XX:MaxRAMPercentage=90.0"
          - name: DOMAIN_NAME # Admin username
            value: "base_domain"
          - name: ADMIN_NAME # Admin username
            value: "AdminServer"
          - name: ADMIN_HOST # Admin username
            value: "AdminContainer"
          - name: ADMIN_LISTEN_PORT # Admin username
            value: "7001"
          - name: MANAGEDSERVER_PORT # Admin username
            value: "8001"
          - name: MANAGED_NAME # Admin username
            value: "infraServer1"
          - name: ADMINISTRATION_PORT_ENABLED # Admin username
            value: "false"
          - name: ADMINISTRATION_PORT # Admin username
            value: "9002"
          - name: PRODUCTION_MODE # Admin username
            value: "prod"
          - name: CONNECTION_STRING # Admin username
            value: "172.16.35.2:1521:DEVADFUTF"
          - name: RCUPREFIX # Admin username
            value: "INFRA52"
        ports:
        - containerPort: 7001

        resources:
          requests: # request resources for every pod 
            memory: "1024Mi" 
            cpu: "1000m"
          limits: # Limit resources for every pod
            memory: "4048Mi"
            cpu: "6000m"

        volumeMounts:
          - name: weblogic-data
            mountPath: "/u01/oracle/user_projects/domains"
      # this for private docker registry you must create it frest 
      imagePullSecrets:
      - name: myregistrykey # docker resistry secrets on same namespace

      securityContext:
        fsGroup: 2000 
      volumes:
      - name: weblogic-data
        persistentVolumeClaim:
          claimName: weblogic-pvc3 # pvc name
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
