apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: weblogic-pvc3
  labels:
    app: weblogic
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn # very important to prvent pod fail attach or mount 
  resources:
    requests:
      storage: 10Gi
